base:
  project_name: Mlops_dvc
  random_state: 22
  target_column: TARGET

data_format:
  type: csv
  seperator: ","

data_source:
  source_path: data_given/winequality.csv

load_data:
  raw_dataset_path: data/raw/winequality.csv

split_data:
  test_dataset_path: data/processed/test_winequality.csv
  train_dataset_path: data/processed/train_winequality.csv
  test_size: 0.3

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.4

reports:
  params: report/params.json
  scores: report/scores.json

model_dir:
  folder: saved_models
  model_name: model.joblib

webapp_model_dir: saved_models/model.joblib
